name: Type Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm and install dependencies
      uses: ./.github/actions/setup-pnpm

    - name: Run type check
      run: pnpm run typecheck 